### ISSUE TITLE
Support external CloudFront

### ISSUE THREAD

**Issue by brian-traceme** [silvermine/serverless-plugin-cloudfront-lambda-edge#34] opened 2019-03-28 21:44 UTC
I'd like to have a serverless js conf to deploy a lambda, attaching it as a Lambda@Edge triggered lambda to a CloudFront that was defined outside of this serverless js conf.

It'd be nice to have a way to specify a CloudFront ID instead of referring to the name of a resource in this conf.

**Comment by jthomerson** [comment] 2019-03-29 00:57
Duplicate of #15

**Closed by jthomerson** 2019-03-29 00:57 UTC
