### ISSUE TITLE
How to specify the cloudfront distribution and the path pattern in serverless.yml?

### ISSUE THREAD

**Issue by hustshawn** [silvermine/serverless-plugin-cloudfront-lambda-edge#9] opened 2018-03-01 10:08 UTC
How to specify the cloudfront distribution and the path pattern in serverless.yml?

**Comment by jthomerson** [comment] 2018-04-10 03:57
Duplicate of #5.

**Closed by jthomerson** 2018-04-10 03:57 UTC

**Comment by hustshawn** [comment] 2018-04-27 04:16
Thanks for let me know.
